//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BannerTag = newBannerTagTable("public", "banner_tag", "")

type bannerTagTable struct {
	postgres.Table

	// Columns
	BannerID postgres.ColumnInteger
	TagID    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BannerTagTable struct {
	bannerTagTable

	EXCLUDED bannerTagTable
}

// AS creates new BannerTagTable with assigned alias
func (a BannerTagTable) AS(alias string) *BannerTagTable {
	return newBannerTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BannerTagTable with assigned schema name
func (a BannerTagTable) FromSchema(schemaName string) *BannerTagTable {
	return newBannerTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BannerTagTable with assigned table prefix
func (a BannerTagTable) WithPrefix(prefix string) *BannerTagTable {
	return newBannerTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BannerTagTable with assigned table suffix
func (a BannerTagTable) WithSuffix(suffix string) *BannerTagTable {
	return newBannerTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBannerTagTable(schemaName, tableName, alias string) *BannerTagTable {
	return &BannerTagTable{
		bannerTagTable: newBannerTagTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newBannerTagTableImpl("", "excluded", ""),
	}
}

func newBannerTagTableImpl(schemaName, tableName, alias string) bannerTagTable {
	var (
		BannerIDColumn = postgres.IntegerColumn("banner_id")
		TagIDColumn    = postgres.IntegerColumn("tag_id")
		allColumns     = postgres.ColumnList{BannerIDColumn, TagIDColumn}
		mutableColumns = postgres.ColumnList{}
	)

	return bannerTagTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		BannerID: BannerIDColumn,
		TagID:    TagIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
