-- +goose Up
CREATE TABLE feature (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  PRIMARY KEY (id)
);

INSERT INTO feature
SELECT generate_series(1, 1000);

SELECT SETVAL('feature_id_seq', (SELECT MAX(id) + 1 FROM feature));

CREATE TABLE banner (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  feature_id INT NOT NULL,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (id),
  FOREIGN KEY (feature_id) REFERENCES feature (id)
);

INSERT INTO banner VALUES
(1,1,'Корм для рыб',true),
(2,2,'Игровые ноутбуки',true),
(3,3,'Компьютерные игры',true);

SELECT SETVAL('banner_id_seq', (SELECT MAX(id) + 1 FROM banner));

CREATE TABLE tag (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  PRIMARY KEY (id)
);

CREATE TABLE banner_tag (
  banner_id INT NOT NULL,
  tag_id INT NOT NULL,

  PRIMARY KEY (banner_id, tag_id),
  FOREIGN KEY (banner_id) REFERENCES banner (id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);

INSERT INTO tag
SELECT generate_series(1, 1000);

INSERT INTO banner_tag VALUES
(1,1),
(1,2),
(1,3),
(2,2),
(3,3);

SELECT SETVAL('tag_id_seq', (SELECT MAX(id) + 1 FROM tag));

CREATE TABLE user_account (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone_number TEXT NULL,
  password TEXT NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO user_account VALUES
(1,'Джо','Байден','baiden@mail.ru','+79884223113','$2a$14$I0vxDZuY.2frMNtok3hW0ezJtgChJoQmsG2roMv3D514WnmJpY1g6');

SELECT SETVAL('user_account_id_seq', (SELECT MAX(id) + 1 FROM user_account));

CREATE TABLE role (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,

  PRIMARY KEY (id)
);

CREATE TABLE user_role (
  user_id INT NOT NULL,
  role_id INT NOT NULL,

  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
);

INSERT INTO role VALUES
(1,'moderator'),
(2,'admin');

INSERT INTO user_role VALUES
(1,2);

SELECT SETVAL('role_id_seq', (SELECT MAX(id) + 1 FROM role));

-- +goose Down
DROP TABLE banner_tag CASCADE;
DROP TABLE banner CASCADE;
DROP TABLE tag CASCADE;
DROP TABLE feature CASCADE;
DROP TABLE user_role CASCADE;
DROP TABLE role CASCADE;
DROP TABLE user_account CASCADE;
